name: Issue with a PMR exposure
description: Use this form to report any issue or problems encountered with an exposure resource on PMR
title: "[Exposure]: "
labels: [exposure]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue with an exposure on PMR. Please fill out the following details.
  - type: input
    id: exposure-url
    attributes:
      label: URI of the exposure
      description: This typically take the form of https[]()://models.physiomeproject.org/e/{exposure_id}; do feel free to point to a specific file subpath within.
      placeholder: https://models.physiomeproject.org/e/1
    validations:
      required: true
  - type: textarea
    id: exposure-issue
    attributes:
      label: The issue encountered with the exposure
      description: Describe the issue you have encountered with the exposure specified above; please also include what you were trying to do, if applicable.
      placeholder: |
        - Archive download is corrupted/missing files.
        - Math in the model does not match the paper.
        - Metadata is incomplete/missing/wrong.
        - Simulation does not run correctly.
        - The link above results in a "We’re sorry, but there seems to be an error…" message.
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: Which browser(s) were you using when you encountered the above issue?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Microsoft Edge
        - Safari
